{% set name = "lume-base" %}
{% set version = "0.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1ae1180c73b9f76d982c5392d356c849b9dd87122749549963a9de26e07d796d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - h5py
    - numpy
    - openpmd-beamphysics
    - pydantic
    - pyyaml

test:
  requires:
    - python {{ python_min }}
    - pytest
  imports:
    - lume
    - lume.base
    - lume.parsers
    - lume.serializers
    - lume.tests
    - lume.variables
  commands:
    - pytest -v --pyargs lume.tests

about:
  home: https://github.com/slaclab/lume-base
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Base classes and architecture for LUME Python projects
  description: |
    Base classes and architecture for LUME Python projects
  doc_url: https://slaclab.github.io/lume-base
  dev_url: https://github.com/slaclab/lume-base

extra:
  recipe-maintainers:
    - ChristopherMayes
    - ken-lauer
