{% set name = "lume-base" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c6671d6acebbb219a3a9ce0e61bcc295323b45eaf435ba27b0e842d051df3153

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - openpmd-beamphysics
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - lume.base

about:
  home: https://github.com/slaclab/lume-base
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Base classes and architecture for LUME Python projects
  description: |
    Base classes and architecture for LUME Python projects
  doc_url: https://slaclab.github.io/lume-base
  dev_url: https://github.com/slaclab/lume-base

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
    - jacquelinegarrahan
